remote_theme: just-the-docs/just-the-docs@v0.10.1
aux_links:
  "POP Forums on GitHub":
    - "https://github.com/POPWorldMedia/POPForums"
footer_content: "&copy;2025, POP World Media, LLC"
title: "POP Forums"
