remote_theme: pmarsceill/just-the-docs@v0.3.2
aux_links:
  "POP Forums on GitHub":
    - "https://github.com/POPWorldMedia/POPForums"
footer_content: "&copy;2020, POP World Media, LLC"
title: "POP Forums"
